/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditsRouteImport } from './routes/edits'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PlantsIndexRouteImport } from './routes/plants.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PlantsSlugRouteImport } from './routes/plants.$slug'
import { Route as EditorsIdRouteImport } from './routes/editors.$id'
import { Route as DraftsIdRouteImport } from './routes/drafts.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin.tags'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminBatchNewRouteImport } from './routes/_authenticated/admin.batch-new'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminProjectsNewRouteImport } from './routes/_authenticated/admin.projects.new'
import { Route as AuthenticatedAdminEditIdRouteImport } from './routes/_authenticated/admin.edit.$id'
import { Route as AuthenticatedAdminCatalogsNewRouteImport } from './routes/_authenticated/admin.catalogs.new'
import { Route as AuthenticatedAdminCatalogsIdRouteImport } from './routes/_authenticated/admin.catalogs.$id'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin.blog.new'
import { Route as AuthenticatedAdminProjectsEditIdRouteImport } from './routes/_authenticated/admin.projects.edit.$id'
import { Route as AuthenticatedAdminBlogEditIdRouteImport } from './routes/_authenticated/admin.blog.edit.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditsRoute = EditsRouteImport.update({
  id: '/edits',
  path: '/edits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsIndexRoute = PlantsIndexRouteImport.update({
  id: '/plants/',
  path: '/plants/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsSlugRoute = PlantsSlugRouteImport.update({
  id: '/plants/$slug',
  path: '/plants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorsIdRoute = EditorsIdRouteImport.update({
  id: '/editors/$id',
  path: '/editors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsIdRoute = DraftsIdRouteImport.update({
  id: '/drafts/$id',
  path: '/drafts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminBatchNewRoute =
  AuthenticatedAdminBatchNewRouteImport.update({
    id: '/admin/batch-new',
    path: '/admin/batch-new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProjectsNewRoute =
  AuthenticatedAdminProjectsNewRouteImport.update({
    id: '/admin/projects/new',
    path: '/admin/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEditIdRoute =
  AuthenticatedAdminEditIdRouteImport.update({
    id: '/admin/edit/$id',
    path: '/admin/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCatalogsNewRoute =
  AuthenticatedAdminCatalogsNewRouteImport.update({
    id: '/admin/catalogs/new',
    path: '/admin/catalogs/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCatalogsIdRoute =
  AuthenticatedAdminCatalogsIdRouteImport.update({
    id: '/admin/catalogs/$id',
    path: '/admin/catalogs/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/admin/blog/new',
    path: '/admin/blog/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProjectsEditIdRoute =
  AuthenticatedAdminProjectsEditIdRouteImport.update({
    id: '/admin/projects/edit/$id',
    path: '/admin/projects/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBlogEditIdRoute =
  AuthenticatedAdminBlogEditIdRouteImport.update({
    id: '/admin/blog/edit/$id',
    path: '/admin/blog/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edits': typeof EditsRoute
  '/explore': typeof ExploreRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drafts/$id': typeof DraftsIdRoute
  '/editors/$id': typeof EditorsIdRoute
  '/plants/$slug': typeof PlantsSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/batch-new': typeof AuthenticatedAdminBatchNewRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/catalogs/$id': typeof AuthenticatedAdminCatalogsIdRoute
  '/admin/catalogs/new': typeof AuthenticatedAdminCatalogsNewRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/admin/blog/edit/$id': typeof AuthenticatedAdminBlogEditIdRoute
  '/admin/projects/edit/$id': typeof AuthenticatedAdminProjectsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edits': typeof EditsRoute
  '/explore': typeof ExploreRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drafts/$id': typeof DraftsIdRoute
  '/editors/$id': typeof EditorsIdRoute
  '/plants/$slug': typeof PlantsSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/plants': typeof PlantsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/batch-new': typeof AuthenticatedAdminBatchNewRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/catalogs/$id': typeof AuthenticatedAdminCatalogsIdRoute
  '/admin/catalogs/new': typeof AuthenticatedAdminCatalogsNewRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/admin/blog/edit/$id': typeof AuthenticatedAdminBlogEditIdRoute
  '/admin/projects/edit/$id': typeof AuthenticatedAdminProjectsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/edits': typeof EditsRoute
  '/explore': typeof ExploreRoute
  '/identify': typeof IdentifyRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drafts/$id': typeof DraftsIdRoute
  '/editors/$id': typeof EditorsIdRoute
  '/plants/$slug': typeof PlantsSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/batch-new': typeof AuthenticatedAdminBatchNewRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/_authenticated/admin/catalogs/$id': typeof AuthenticatedAdminCatalogsIdRoute
  '/_authenticated/admin/catalogs/new': typeof AuthenticatedAdminCatalogsNewRoute
  '/_authenticated/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
  '/_authenticated/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/_authenticated/admin/blog/edit/$id': typeof AuthenticatedAdminBlogEditIdRoute
  '/_authenticated/admin/projects/edit/$id': typeof AuthenticatedAdminProjectsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edits'
    | '/explore'
    | '/identify'
    | '/login'
    | '/profile'
    | '/search'
    | '/signup'
    | '/blog/$slug'
    | '/drafts/$id'
    | '/editors/$id'
    | '/plants/$slug'
    | '/projects/$id'
    | '/tags/$slug'
    | '/blog/'
    | '/plants/'
    | '/projects/'
    | '/admin/applications'
    | '/admin/batch-new'
    | '/admin/new'
    | '/admin/tags'
    | '/admin/'
    | '/admin/blog/new'
    | '/admin/catalogs/$id'
    | '/admin/catalogs/new'
    | '/admin/edit/$id'
    | '/admin/projects/new'
    | '/admin/blog/edit/$id'
    | '/admin/projects/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edits'
    | '/explore'
    | '/identify'
    | '/login'
    | '/profile'
    | '/search'
    | '/signup'
    | '/blog/$slug'
    | '/drafts/$id'
    | '/editors/$id'
    | '/plants/$slug'
    | '/projects/$id'
    | '/tags/$slug'
    | '/blog'
    | '/plants'
    | '/projects'
    | '/admin/applications'
    | '/admin/batch-new'
    | '/admin/new'
    | '/admin/tags'
    | '/admin'
    | '/admin/blog/new'
    | '/admin/catalogs/$id'
    | '/admin/catalogs/new'
    | '/admin/edit/$id'
    | '/admin/projects/new'
    | '/admin/blog/edit/$id'
    | '/admin/projects/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/edits'
    | '/explore'
    | '/identify'
    | '/login'
    | '/profile'
    | '/search'
    | '/signup'
    | '/blog/$slug'
    | '/drafts/$id'
    | '/editors/$id'
    | '/plants/$slug'
    | '/projects/$id'
    | '/tags/$slug'
    | '/blog/'
    | '/plants/'
    | '/projects/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/batch-new'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/new'
    | '/_authenticated/admin/catalogs/$id'
    | '/_authenticated/admin/catalogs/new'
    | '/_authenticated/admin/edit/$id'
    | '/_authenticated/admin/projects/new'
    | '/_authenticated/admin/blog/edit/$id'
    | '/_authenticated/admin/projects/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EditsRoute: typeof EditsRoute
  ExploreRoute: typeof ExploreRoute
  IdentifyRoute: typeof IdentifyRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DraftsIdRoute: typeof DraftsIdRoute
  EditorsIdRoute: typeof EditorsIdRoute
  PlantsSlugRoute: typeof PlantsSlugRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  TagsSlugRoute: typeof TagsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PlantsIndexRoute: typeof PlantsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edits': {
      id: '/edits'
      path: '/edits'
      fullPath: '/edits'
      preLoaderRoute: typeof EditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/': {
      id: '/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof PlantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$slug': {
      id: '/plants/$slug'
      path: '/plants/$slug'
      fullPath: '/plants/$slug'
      preLoaderRoute: typeof PlantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editors/$id': {
      id: '/editors/$id'
      path: '/editors/$id'
      fullPath: '/editors/$id'
      preLoaderRoute: typeof EditorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/$id': {
      id: '/drafts/$id'
      path: '/drafts/$id'
      fullPath: '/drafts/$id'
      preLoaderRoute: typeof DraftsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/batch-new': {
      id: '/_authenticated/admin/batch-new'
      path: '/admin/batch-new'
      fullPath: '/admin/batch-new'
      preLoaderRoute: typeof AuthenticatedAdminBatchNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/projects/new': {
      id: '/_authenticated/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AuthenticatedAdminProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/edit/$id': {
      id: '/_authenticated/admin/edit/$id'
      path: '/admin/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/catalogs/new': {
      id: '/_authenticated/admin/catalogs/new'
      path: '/admin/catalogs/new'
      fullPath: '/admin/catalogs/new'
      preLoaderRoute: typeof AuthenticatedAdminCatalogsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/catalogs/$id': {
      id: '/_authenticated/admin/catalogs/$id'
      path: '/admin/catalogs/$id'
      fullPath: '/admin/catalogs/$id'
      preLoaderRoute: typeof AuthenticatedAdminCatalogsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/blog/new': {
      id: '/_authenticated/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/projects/edit/$id': {
      id: '/_authenticated/admin/projects/edit/$id'
      path: '/admin/projects/edit/$id'
      fullPath: '/admin/projects/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/blog/edit/$id': {
      id: '/_authenticated/admin/blog/edit/$id'
      path: '/admin/blog/edit/$id'
      fullPath: '/admin/blog/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminBatchNewRoute: typeof AuthenticatedAdminBatchNewRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
  AuthenticatedAdminCatalogsIdRoute: typeof AuthenticatedAdminCatalogsIdRoute
  AuthenticatedAdminCatalogsNewRoute: typeof AuthenticatedAdminCatalogsNewRoute
  AuthenticatedAdminEditIdRoute: typeof AuthenticatedAdminEditIdRoute
  AuthenticatedAdminProjectsNewRoute: typeof AuthenticatedAdminProjectsNewRoute
  AuthenticatedAdminBlogEditIdRoute: typeof AuthenticatedAdminBlogEditIdRoute
  AuthenticatedAdminProjectsEditIdRoute: typeof AuthenticatedAdminProjectsEditIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminBatchNewRoute: AuthenticatedAdminBatchNewRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
  AuthenticatedAdminCatalogsIdRoute: AuthenticatedAdminCatalogsIdRoute,
  AuthenticatedAdminCatalogsNewRoute: AuthenticatedAdminCatalogsNewRoute,
  AuthenticatedAdminEditIdRoute: AuthenticatedAdminEditIdRoute,
  AuthenticatedAdminProjectsNewRoute: AuthenticatedAdminProjectsNewRoute,
  AuthenticatedAdminBlogEditIdRoute: AuthenticatedAdminBlogEditIdRoute,
  AuthenticatedAdminProjectsEditIdRoute: AuthenticatedAdminProjectsEditIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EditsRoute: EditsRoute,
  ExploreRoute: ExploreRoute,
  IdentifyRoute: IdentifyRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  DraftsIdRoute: DraftsIdRoute,
  EditorsIdRoute: EditorsIdRoute,
  PlantsSlugRoute: PlantsSlugRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  TagsSlugRoute: TagsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PlantsIndexRoute: PlantsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
