-- Seed: 内蒙古（2009） 省级重点保护野生植物名录. province=内蒙古. 130 taxa.
-- Source: 内蒙古自治区重点保护草原野生植物名录｜内蒙古自治区人民政府批准发布｜2009-07-30 发布｜自治区重点保护草原野生植物（不是全口径野生植物名录）；中国珍稀濒危植物信息系统转载，页面注明来源为内蒙古自治区网
DELETE FROM public.conservation_taxa t USING public.conservation_lists l
  WHERE t.list_id = l.id AND l.kind = 'protected' AND l.province = '内蒙古';
DELETE FROM public.conservation_lists WHERE kind = 'protected' AND province = '内蒙古';
WITH new_list AS (
  INSERT INTO public.conservation_lists (kind, name, province, version, effective_date, source_url, source_note)
  VALUES ('protected', '内蒙古（2009）', '内蒙古', '2009', DATE '2009-07-30', 'https://www.iplant.cn/rep/news/23', '内蒙古自治区重点保护草原野生植物名录｜内蒙古自治区人民政府批准发布｜2009-07-30 发布｜自治区重点保护草原野生植物（不是全口径野生植物名录）；中国珍稀濒危植物信息系统转载，页面注明来源为内蒙古自治区网')
  RETURNING id
)
INSERT INTO public.conservation_taxa (list_id, scientific_name, normalized_name, chinese_name, status, rank, excluded_names)
SELECT nl.id, v.sci, v.norm, v.zh, '省级', v.rank, NULL::text[] FROM new_list nl, (VALUES
  ('Equisetum arvense', 'equisetum arvense', '问荆', 'species'),
  ('Pteridium aquilinum var. latiusculum', 'pteridium aquilinum', '蕨菜', 'species'),
  ('Ephrdra sinica', 'ephrdra sinica', '草麻黄', 'species'),
  ('Ephedra rhytidosperma', 'ephedra rhytidosperma', '斑子麻黄', 'species'),
  ('Ephedra equisetina', 'ephedra equisetina', '木贼麻黄', 'species'),
  ('Ephedra monosperma', 'ephedra monosperma', '单子麻黄', 'species'),
  ('Ephedra intermedia', 'ephedra intermedia', '中麻黄', 'species'),
  ('Rheum franzenbachii', 'rheum franzenbachii', '华北大黄', 'species'),
  ('Calligonum alaschanicum', 'calligonum alaschanicum', '阿拉善沙拐枣', 'species'),
  ('Calligonum mongolicum', 'calligonum mongolicum', '沙拐枣', 'species'),
  ('Atraphaxis tortuosa', 'atraphaxis tortuosa', '圆叶木蓼', 'species'),
  ('Atraphaxis bracteata', 'atraphaxis bracteata', '沙木蓼', 'species'),
  ('Polygonum bistorta', 'polygonum bistorta', '拳参', 'species'),
  ('Haloxylon ammodendron', 'haloxylon ammodendron', '梭梭', 'species'),
  ('Auabasis brevifolia', 'auabasis brevifolia', '短叶假木贼', 'species'),
  ('Iljinia regelii', 'iljinia regelii', '戈壁藜', 'species'),
  ('Gymnocarpos przewalskii', 'gymnocarpos przewalskii', '裸果木', 'species'),
  ('Pseudostellaria heterophylla', 'pseudostellaria heterophylla', '孩儿参', 'species'),
  ('Stellaria dichotoma Var. linearis', 'stellaria dichotoma', '银柴胡', 'species'),
  ('Melandrium alaschanicum', 'melandrium alaschanicum', '贺兰山女娄菜', 'species'),
  ('Paeonia lactiflora', 'paeonia lactiflora', '芍 药', 'species'),
  ('Trollius chinensis', 'trollius chinensis', '金莲花', 'species'),
  ('Trollius ledebouri', 'trollius ledebouri', '短瓣金莲花', 'species'),
  ('Cimicifuga dahurica', 'cimicifuga dahurica', '兴安升麻', 'species'),
  ('Aconitum kusnezoffii', 'aconitum kusnezoffii', '草乌头', 'species'),
  ('Aconitum yinschanicum', 'aconitum yinschanicum', '阴山乌头', 'species'),
  ('Anemone silvestris', 'anemone silvestris', '大花银莲花', 'species'),
  ('Pulsatilla chinensis', 'pulsatilla chinensis', '白头翁', 'species'),
  ('Clematis fruticlsa', 'clematis fruticlsa', '灌木铁线莲', 'species'),
  ('Berberis caroli', 'berberis caroli', '鄂尔多斯小檗', 'species'),
  ('Pugionium cornutum', 'pugionium cornutum', '沙芥', 'species'),
  ('Pugionium calcaratum', 'pugionium calcaratum', '距果沙芥', 'species'),
  ('Sedum aizoon', 'sedum aizoon', '费菜', 'species'),
  ('Potaninia mongolica', 'potaninia mongolica', '绵 刺', 'species'),
  ('Ptentilla parvifolia', 'ptentilla parvifolia', '小叶金露梅', 'species'),
  ('Potentilla glabra', 'potentilla glabra', '银露梅', 'species'),
  ('Prinsepia uniflora', 'prinsepia uniflora', '蕤核', 'species'),
  ('Prunus mongolica', 'prunus mongolica', '蒙古扁桃', 'species'),
  ('Prunus pedunculat', 'prunus pedunculat', '柄扁桃', 'species'),
  ('Sophora alopecuroides', 'sophora alopecuroides', '苦豆子', 'species'),
  ('Sophora flavescens', 'sophora flavescens', '苦参', 'species'),
  ('Ammopiptanthus mongolicus', 'ammopiptanthus mongolicus', '沙冬青', 'species'),
  ('Medicago alaschanica', 'medicago alaschanica', '阿拉善苜蓿', 'species'),
  ('Medicago falcata', 'medicago falcata', '黄花苜蓿', 'species'),
  ('Caragana roborovskyi', 'caragana roborovskyi', '荒漠锦鸡儿', 'species'),
  ('Spongiocarpella grubovii', 'spongiocarpella grubovii', '红花海绵豆', 'species'),
  ('Chesneya mongolica', 'chesneya mongolica', '蒙古雀儿豆', 'species'),
  ('Astragalus membranaceus', 'astragalus membranaceus', '膜荚黄芪', 'species'),
  ('Astragalus mongholicus', 'astragalus mongholicus', '内蒙黄芪', 'species'),
  ('Astyagalus hoantchy', 'astyagalus hoantchy', '粗壮黄耆', 'species'),
  ('Astragalus complanatus', 'astragalus complanatus', '扁茎黄芪', 'species'),
  ('Astragalus alaschanus', 'astragalus alaschanus', '阿拉善黄芪', 'species'),
  ('Orytropis meimonggolica', 'orytropis meimonggolica', '内蒙古棘豆', 'species'),
  ('Glycyrrhiza uralensis', 'glycyrrhiza uralensis', '甘 草', 'species'),
  ('Glycyrrhiza squamulosa', 'glycyrrhiza squamulosa', '圆果甘草', 'species'),
  ('Glycyrrhiza psllidiflora', 'glycyrrhiza psllidiflora', '刺果甘草', 'species'),
  ('Hedysarum fruticosum', 'hedysarum fruticosum', '山竹岩黄芪', 'species'),
  ('Alhagi Pseudalhagi', 'alhagi pseudalhagi', '骆驼刺', 'species'),
  ('Vicia amoena var. oblongifolia', 'vicia amoena', '狭叶山野豌豆', 'species'),
  ('Nitraria tangutorum', 'nitraria tangutorum', '白剌', 'species'),
  ('Tetraena mongolica', 'tetraena mongolica', '四合木', 'species'),
  ('Zygophyllum xanthoxylum', 'zygophyllum xanthoxylum', '霸王', 'species'),
  ('Haplophyllum tragacanthoides', 'haplophyllum tragacanthoides', '针枝芸香', 'species'),
  ('Dictamnus dasycarpus', 'dictamnus dasycarpus', '白鲜', 'species'),
  ('Zanthaylum schinifolium', 'zanthaylum schinifolium', '香椒子', 'species'),
  ('Polygala tenuifolia', 'polygala tenuifolia', '远志', 'species'),
  ('Polygala sibirica', 'polygala sibirica', '卵叶远志', 'species'),
  ('Reaumuria trigyna', 'reaumuria trigyna', '长叶红砂', 'species'),
  ('Helianthemum soongolicum', 'helianthemum soongolicum', '半日花', 'species'),
  ('Cynomorium songaricum', 'cynomorium songaricum', '锁阳', 'species'),
  ('Bupleurum scorzonerifolium', 'bupleurum scorzonerifolium', '红柴胡', 'species'),
  ('Bupleurum sibiricum', 'bupleurum sibiricum', '兴安柴胡', 'species'),
  ('Seseli intramongolicum', 'seseli intramongolicum', '内蒙古西风芹', 'species'),
  ('Cnidium monnier', 'cnidium monnier', '蛇床', 'species'),
  ('Saposhnikovia divaricata', 'saposhnikovia divaricata', '防风', 'species'),
  ('Peucedanum terebinthaceum', 'peucedanum terebinthaceum', '石防风', 'species'),
  ('Androsace alashanica', 'androsace alashanica', '阿拉善点地梅', 'species'),
  ('Limonium aureum', 'limonium aureum', '黄花补血草', 'species'),
  ('Limonium bicolor', 'limonium bicolor', '二色补血草', 'species'),
  ('Syringa pinnatifolia var. holanshanensis', 'syringa pinnatifolia', '贺兰山丁香', 'species'),
  ('Gentiana dohurica', 'gentiana dohurica', '达乌里秦艽', 'species'),
  ('Gentiana macrophylla', 'gentiana macrophylla', '秦艽', 'species'),
  ('Gentiana scabra', 'gentiana scabra', '龙胆', 'species'),
  ('Apocynum venetum', 'apocynum venetum', '罗布麻', 'species'),
  ('Cynanchum komarovii', 'cynanchum komarovii', '牛心朴子', 'species'),
  ('Cynanchum Paniculatum', 'cynanchum paniculatum', '徐长卿', 'species'),
  ('Caryopteris monlica', 'caryopteris monlica', '蒙古莸', 'species'),
  ('Scutellria baicalensis', 'scutellria baicalensis', '黄芩', 'species'),
  ('Scutellaria alaschanica', 'scutellaria alaschanica', '阿拉善黄芩', 'species'),
  ('Dracocephalum rigidulum', 'dracocephalum rigidulum', '微硬毛青兰', 'species'),
  ('Leonurus sibiricus', 'leonurus sibiricus', '细叶益母草', 'species'),
  ('Panzeria alaschanlca', 'panzeria alaschanlca', '白龙昌菜', 'species'),
  ('Mentha haplocalyx', 'mentha haplocalyx', '薄荷', 'species'),
  ('Elsholtzia ciliata', 'elsholtzia ciliata', '香薷', 'species'),
  ('Licium ruthenicum', 'licium ruthenicum', '黑果枸杞', 'species'),
  ('Orobanche pycnostachya', 'orobanche pycnostachya', '黄花列当', 'species'),
  ('Boschniakia rossica', 'boschniakia rossica', '草苁蓉', 'species'),
  ('Cistanche deserticola', 'cistanche deserticola', '肉苁蓉', 'species'),
  ('Cistanche salsa', 'cistanche salsa', '盐生苁蓉', 'species'),
  ('Cistanche sinensis', 'cistanche sinensis', '沙苁蓉', 'species'),
  ('Actinostemma lobatum', 'actinostemma lobatum', '盒子草', 'species'),
  ('Platycodon grandiflorum', 'platycodon grandiflorum', '桔梗', 'species'),
  ('Campanula punctata', 'campanula punctata', '紫斑风铃草', 'species'),
  ('Adenophora gmelinii', 'adenophora gmelinii', '狭叶沙参', 'species'),
  ('Adenophora tetraphylla', 'adenophora tetraphylla', '轮叶沙参', 'species'),
  ('Adenophora stenanthina', 'adenophora stenanthina', '长柱沙参', 'species'),
  ('Brachanthemum gobicum', 'brachanthemum gobicum', '戈壁短舌菊', 'species'),
  ('Stilpnolepis centiflora', 'stilpnolepis centiflora', '百花蒿', 'species'),
  ('Atractylodes lancea', 'atractylodes lancea', '苍术', 'species'),
  ('Takeikadczukia lomonossowii', 'takeikadczukia lomonossowii', '蝟菊', 'species'),
  ('Jurinea mongolica', 'jurinea mongolica', '蒙疆苓菊', 'species'),
  ('Saussurea alashanica', 'saussurea alashanica', '阿拉善风毛菊', 'species'),
  ('Alisma orientale', 'alisma orientale', '泽泻', 'species'),
  ('Miscanthus sacchariflorus', 'miscanthus sacchariflorus', '荻', 'species'),
  ('Typhonium trifoliatum', 'typhonium trifoliatum', '三叶犁头尖', 'species'),
  ('Anemarrhena asphodeloides', 'anemarrhena asphodeloides', '知母', 'species'),
  ('Hemerocallis minor', 'hemerocallis minor', '小黄花菜', 'species'),
  ('Tulipa uniflora', 'tulipa uniflora', '单花郁金香', 'species'),
  ('Lilium concolor', 'lilium concolor', '有斑百合', 'species'),
  ('Lilium dauricum', 'lilium dauricum', '毛百合', 'species'),
  ('Lilium Pumilum', 'lilium pumilum', '山丹', 'species'),
  ('Allium mogolicum', 'allium mogolicum', '蒙古葱', 'species'),
  ('Allium alaschanicum', 'allium alaschanicum', '阿拉善葱', 'species'),
  ('Polygonatum odoratum', 'polygonatum odoratum', '玉竹', 'species'),
  ('Polygonatum sibiricum', 'polygonatum sibiricum', '黄精', 'species'),
  ('Tulotis asiatica', 'tulotis asiatica', '蜻蜓兰', 'species'),
  ('Herminium monorchis', 'herminium monorchis', '角盘兰', 'species'),
  ('Gymnadenia conopsea', 'gymnadenia conopsea', '手掌参', 'species'),
  ('Spiranthes sinensis', 'spiranthes sinensis', '绶草', 'species'),
  ('Malaxis monophyllos', 'malaxis monophyllos', '沼兰', 'species')
) AS v(sci, norm, zh, rank);
