-- Seed: 云南（2023） 省级重点保护野生植物名录. province=云南. 77 taxa.
-- Source: 云南省重点保护野生植物名录｜云南省林业和草原局、云南省农业农村厅公告（2023年第11号）｜2023-12-15 发布｜省级重点保护野生植物；含种级和属级条目；云南省林业和草原局官方公告及附件
DELETE FROM public.conservation_taxa t USING public.conservation_lists l
  WHERE t.list_id = l.id AND l.kind = 'protected' AND l.province = '云南';
DELETE FROM public.conservation_lists WHERE kind = 'protected' AND province = '云南';
WITH new_list AS (
  INSERT INTO public.conservation_lists (kind, name, province, version, effective_date, source_url, source_note)
  VALUES ('protected', '云南（2023）', '云南', '2023', DATE '2023-12-15', 'https://lcj.yn.gov.cn/html/2023/gongshigonggao_1218/70386.html', '云南省重点保护野生植物名录｜云南省林业和草原局、云南省农业农村厅公告（2023年第11号）｜2023-12-15 发布｜省级重点保护野生植物；含种级和属级条目；云南省林业和草原局官方公告及附件')
  RETURNING id
)
INSERT INTO public.conservation_taxa (list_id, scientific_name, normalized_name, chinese_name, status, rank, excluded_names)
SELECT nl.id, v.sci, v.norm, v.zh, '省级', v.rank, NULL::text[] FROM new_list nl, (VALUES
  ('Didymochlaena sinuosa', 'didymochlaena sinuosa', '翼囊蕨', 'species'),
  ('Neocheiropteris palmatopedata', 'neocheiropteris palmatopedata', '扇蕨', 'species'),
  ('Keteleeria evelyniana var. pendula', 'keteleeria evelyniana', '蒙自油杉', 'species'),
  ('Nymphaea tetragona', 'nymphaea tetragona', '茈碧莲', 'species'),
  ('Magnolia phanerophlebia', 'magnolia phanerophlebia', '显脉木兰', 'species'),
  ('Manglietia lucida', 'manglietia lucida', '亮叶木莲', 'species'),
  ('Manglietia ovoidea', 'manglietia ovoidea', '卵果木莲', 'species'),
  ('Michelia glaucophylla', 'michelia glaucophylla', '粉背含笑', 'species'),
  ('Michelia iteophylla', 'michelia iteophylla', '鼠刺含笑', 'species'),
  ('Michelia lacei', 'michelia lacei', '壮丽含笑', 'species'),
  ('Talauma hodgsonii', 'talauma hodgsonii', '盖裂木', 'species'),
  ('Yulania campbellii', 'yulania campbellii', '滇藏玉兰', 'species'),
  ('Orophea yunnanensis', 'orophea yunnanensis', '云南澄广花', 'species'),
  ('Polyalthiopsis verrucipes', 'polyalthiopsis verrucipes', '疣叶暗罗', 'species'),
  ('Wuodendron praecox', 'wuodendron praecox', '征镒木', 'species'),
  ('Camphora glandulifera', 'camphora glandulifera', '云南樟', 'species'),
  ('Alseodaphnopsis petiolaris', 'alseodaphnopsis petiolaris', '长柄北油丹', 'species'),
  ('Cremastra malipoensis', 'cremastra malipoensis', '麻栗坡杜鹃兰', 'species'),
  ('Bulbophyllum yingjiangense', 'bulbophyllum yingjiangense', '盈江卷瓣兰', 'species'),
  ('Phalaenopsis spp.', 'phalaenopsis', '蝴蝶兰属所有种（国家二级保护植物罗氏蝴蝶兰、麻栗坡蝴蝶兰、华西蝴蝶兰除外）', 'genus'),
  ('Vanda spp.', 'vanda', '万代兰属所有种（国家二级保护植物大花万代兰除外）', 'genus'),
  ('Holcoglossum spp.', 'holcoglossum', '槽舌兰属所有种', 'genus'),
  ('Trachycarpus princeps', 'trachycarpus princeps', '贡山棕榈', 'species'),
  ('Musa ruiliensis', 'musa ruiliensis', '瑞丽芭蕉', 'species'),
  ('Amomum mengtzense', 'amomum mengtzense', '蒙自砂仁', 'species'),
  ('Cephalostachyum mannii', 'cephalostachyum mannii', '独龙江空竹', 'species'),
  ('Chimonocalamus cibarius', 'chimonocalamus cibarius', '御香竹', 'species'),
  ('Meconopsis smithiana', 'meconopsis smithiana', '贡山绿绒蒿', 'species'),
  ('Fibraurea recisa', 'fibraurea recisa', '天仙藤', 'species'),
  ('Dumasia prazeri', 'dumasia prazeri', '缅北山黑豆', 'species'),
  ('Elaeagnus bambusetorum', 'elaeagnus bambusetorum', '竹生羊奶子', 'species'),
  ('Artocarpus gongshanensis', 'artocarpus gongshanensis', '贡山波罗蜜', 'species'),
  ('Antiaris toxicaria', 'antiaris toxicaria', '见血封喉', 'species'),
  ('Cyclobalanopsis tomentosinervis', 'cyclobalanopsis tomentosinervis', '毛脉青冈', 'species'),
  ('Quercus marlipoensis', 'quercus marlipoensis', '麻栗坡栎', 'species'),
  ('Trigonobalanus verticillata', 'trigonobalanus verticillata', '轮叶三棱栎', 'species'),
  ('Lithocarpus longinux', 'lithocarpus longinux', '长果柯', 'species'),
  ('Carya poilanei', 'carya poilanei', '波氏山核桃', 'species'),
  ('Carya tonkinensis', 'carya tonkinensis', '越南山核桃', 'species'),
  ('Begonia longicarpa', 'begonia longicarpa', '长果秋海棠', 'species'),
  ('Begonia rhynchocarpa', 'begonia rhynchocarpa', '喙果秋海棠', 'species'),
  ('Rinorea erianthera', 'rinorea erianthera', '毛蕊三角车', 'species'),
  ('Garcinia pedunculata', 'garcinia pedunculata', '大果藤黄', 'species'),
  ('Tsaiodendron dioicum', 'tsaiodendron dioicum', '希陶木', 'species'),
  ('Protium yunnanense', 'protium yunnanense', '滇马蹄果', 'species'),
  ('Mangifera spp.', 'mangifera', '杧果属所有种*（国家二级保护植物林生杧果除外）', 'genus'),
  ('Acer calcaratum', 'acer calcaratum', '三裂槭', 'species'),
  ('Acer crassum', 'acer crassum', '厚叶槭', 'species'),
  ('Acer wardii', 'acer wardii', '滇藏槭', 'species'),
  ('Citrus macroptera var. kerrii', 'citrus macroptera', '大翼厚皮橙', 'species'),
  ('Pterygota alata', 'pterygota alata', '翅苹婆', 'species'),
  ('Vatica xishuangbannaensis', 'vatica xishuangbannaensis', '版纳青梅', 'species'),
  ('Parashorea buchananii', 'parashorea buchananii', '盈江柳桉', 'species'),
  ('Baimashania pulvinata', 'baimashania pulvinata', '白马芥', 'species'),
  ('Urobotrya latisquama', 'urobotrya latisquama', '尾球木', 'species'),
  ('Mastixia euonymoides', 'mastixia euonymoides', '八蕊单室茱萸', 'species'),
  ('Primula caldaria', 'primula caldaria', '匍枝粉报春', 'species'),
  ('Primula chapaensis', 'primula chapaensis', '马关报春', 'species'),
  ('Primula pauliana', 'primula pauliana', '总序报春', 'species'),
  ('Camellia hekouensis', 'camellia hekouensis', '河口长梗茶', 'species'),
  ('Pyrenaria oblongicarpa', 'pyrenaria oblongicarpa', '长果核果茶', 'species'),
  ('Camellia gilbertii', 'camellia gilbertii', '中越短蕊茶', 'species'),
  ('Parastyrax macrophyllus', 'parastyrax macrophyllus', '大叶茉莉果', 'species'),
  ('Huodendron tibeticum', 'huodendron tibeticum', '西藏山茉莉', 'species'),
  ('Rhododendron farinosum', 'rhododendron farinosum', '钝头杜鹃', 'species'),
  ('Rhododendron longipedicellatum', 'rhododendron longipedicellatum', '长梗杜鹃', 'species'),
  ('Rhododendron mallotum', 'rhododendron mallotum', '羊毛杜鹃', 'species'),
  ('Rhododendron platyphyllum', 'rhododendron platyphyllum', '阔叶杜鹃', 'species'),
  ('Rhododendron tsaii', 'rhododendron tsaii', '昭通杜鹃', 'species'),
  ('Rhododendron vialii', 'rhododendron vialii', '红马银花', 'species'),
  ('Jasminum honghoense', 'jasminum honghoense', '红河素馨', 'species'),
  ('Oreocharis mileensis', 'oreocharis mileensis', '弥勒苣苔', 'species'),
  ('Petrocosmea grandiflora', 'petrocosmea grandiflora', '大花石蝴蝶', 'species'),
  ('Buddleja delavayi', 'buddleja delavayi', '腺叶醉鱼草', 'species'),
  ('Buddleja sessilifolia', 'buddleja sessilifolia', '无柄醉鱼草', 'species'),
  ('Clerodendrum brachystemon', 'clerodendrum brachystemon', '短蕊大青', 'species'),
  ('Ardisia dasyrhizomatica', 'ardisia dasyrhizomatica', '粗茎紫金牛', 'species')
) AS v(sci, norm, zh, rank);
