-- Seed: 国家重点保护野生植物名录 (2021). Generated from official gov.cn PDF.
-- 455 species + 40 categories. * (农业农村部管辖) markers dropped from names.
-- Idempotent: clears any prior 国家(2021) protected list before re-inserting.

DELETE FROM public.conservation_taxa t USING public.conservation_lists l
  WHERE t.list_id = l.id AND l.kind = 'protected' AND l.province = '国家';
DELETE FROM public.conservation_lists WHERE kind = 'protected' AND province = '国家';

WITH new_list AS (
  INSERT INTO public.conservation_lists (kind, name, province, version, effective_date, source_url, source_note)
  VALUES ('protected', '国家（2021）', '国家', '2021', DATE '2021-09-07',
          'https://www.gov.cn/zhengce/zhengceku/2021-09/09/content_5636409.htm',
          '《国家重点保护野生植物名录》｜国家林业和草原局、农业农村部公告（2021年第15号）｜2021-08-07 国务院批准，2021-09-07 施行｜共 455 种和 40 类。')
  RETURNING id
)
INSERT INTO public.conservation_taxa (list_id, scientific_name, normalized_name, chinese_name, status, rank, excluded_names)
SELECT nl.id, v.sci, v.norm, v.zh, v.status, v.rank, v.excl
FROM new_list nl, (VALUES
  ('Leucobryum juniperoideum', 'leucobryum juniperoideum', '桧叶白发藓', '二级', 'species', NULL::text[]),
  ('Sphagnum multifibrosum', 'sphagnum multifibrosum', '多纹泥炭藓', '二级', 'species', NULL::text[]),
  ('Sphagnum squarrosum', 'sphagnum squarrosum', '粗叶泥炭藓', '二级', 'species', NULL::text[]),
  ('Takakia ceratophylla', 'takakia ceratophylla', '角叶藻苔', '二级', 'species', NULL::text[]),
  ('Takakia lepidozioides', 'takakia lepidozioides', '藻苔', '二级', 'species', NULL::text[]),
  ('Huperzia spp.', 'huperzia', '石杉属 （所有种）', '二级', 'genus', NULL::text[]),
  ('Phlegmariurus spp.', 'phlegmariurus', '马尾杉属（所有种）', '二级', 'genus', NULL::text[]),
  ('Isoëtes spp.', 'isoetes', '水韭属 （所有种）', '一级', 'genus', NULL::text[]),
  ('Helminthostachys zeylanica', 'helminthostachys zeylanica', '七指蕨', '二级', 'species', NULL::text[]),
  ('Ophioglossum pendulum', 'ophioglossum pendulum', '带状瓶尔小草', '二级', 'species', NULL::text[]),
  ('Angiopteris spp.', 'angiopteris', '观音座莲属（所有种）', '二级', 'genus', NULL::text[]),
  ('Christensenia assamica', 'christensenia assamica', '天星蕨', '二级', 'species', NULL::text[]),
  ('Cibotium spp.', 'cibotium', '金毛狗属（所有种）', '二级', 'genus', NULL::text[]),
  ('Cyatheaceae spp.', 'cyatheaceae', '桫椤科（所有种，小黑桫椤和粗齿桫椤除外）', '二级', 'family', ARRAY['alsophila metteniana','alsophila denticulata']),
  ('Adiantum nelumboides', 'adiantum nelumboides', '荷叶铁线蕨', '一级', 'species', NULL::text[]),
  ('Ceratopteris spp.', 'ceratopteris', '水蕨属（所有种）', '二级', 'genus', NULL::text[]),
  ('Cystopteris chinensis', 'cystopteris chinensis', '光叶蕨', '一级', 'species', NULL::text[]),
  ('Asplenium komarovii', 'asplenium komarovii', '对开蕨', '二级', 'species', NULL::text[]),
  ('Brainea insignis', 'brainea insignis', '苏铁蕨', '二级', 'species', NULL::text[]),
  ('Platycerium wallichii', 'platycerium wallichii', '鹿角蕨', '二级', 'species', NULL::text[]),
  ('Cycas spp.', 'cycas', '苏铁属（所有种）', '一级', 'genus', NULL::text[]),
  ('Ginkgo biloba', 'ginkgo biloba', '银杏', '一级', 'species', NULL::text[]),
  ('Podocarpus spp.', 'podocarpus', '罗汉松属（所有种）', '二级', 'genus', NULL::text[]),
  ('Calocedrus macrolepis', 'calocedrus macrolepis', '翠柏', '二级', 'species', NULL::text[]),
  ('Calocedrus rupestris', 'calocedrus rupestris', '岩生翠柏', '二级', 'species', NULL::text[]),
  ('Chamaecyparis formosensis', 'chamaecyparis formosensis', '红桧', '二级', 'species', NULL::text[]),
  ('Cupressus chengiana', 'cupressus chengiana', '岷江柏木', '二级', 'species', NULL::text[]),
  ('Cupressus gigantea', 'cupressus gigantea', '巨柏', '一级', 'species', NULL::text[]),
  ('Cupressus torulosa', 'cupressus torulosa', '西藏柏木', '一级', 'species', NULL::text[]),
  ('Fokienia hodginsii', 'fokienia hodginsii', '福建柏', '二级', 'species', NULL::text[]),
  ('Glyptostrobus pensilis', 'glyptostrobus pensilis', '水松', '一级', 'species', NULL::text[]),
  ('Metasequoia glyptostroboides', 'metasequoia glyptostroboides', '水杉', '一级', 'species', NULL::text[]),
  ('Taiwania cryptomerioides', 'taiwania cryptomerioides', '台湾杉（秃杉）', '二级', 'species', NULL::text[]),
  ('Thuja koraiensis', 'thuja koraiensis', '朝鲜崖柏', '二级', 'species', NULL::text[]),
  ('Thuja sutchuenensis', 'thuja sutchuenensis', '崖柏', '一级', 'species', NULL::text[]),
  ('Xanthocyparis vietnamensis', 'xanthocyparis vietnamensis', '越南黄金柏', '二级', 'species', NULL::text[]),
  ('Amentotaxus spp.', 'amentotaxus', '穗花杉属（所有种）', '二级', 'genus', NULL::text[]),
  ('Cephalotaxus hainanensis', 'cephalotaxus hainanensis', '海南粗榧', '二级', 'species', NULL::text[]),
  ('Cephalotaxus lanceolata', 'cephalotaxus lanceolata', '贡山三尖杉', '二级', 'species', NULL::text[]),
  ('Cephalotaxus oliveri', 'cephalotaxus oliveri', '篦子三尖杉', '二级', 'species', NULL::text[]),
  ('Pseudotaxus chienii', 'pseudotaxus chienii', '白豆杉', '二级', 'species', NULL::text[]),
  ('Taxus spp.', 'taxus', '红豆杉属（所有种）', '一级', 'genus', NULL::text[]),
  ('Torreya spp.', 'torreya', '榧树属（所有种）', '二级', 'genus', NULL::text[]),
  ('Abies beshanzuensis', 'abies beshanzuensis', '百山祖冷杉', '一级', 'species', NULL::text[]),
  ('Abies beshanzuensis var. ziyuanensis', 'abies beshanzuensis', '资源冷杉', '一级', 'species', NULL::text[]),
  ('Abies chensiensis', 'abies chensiensis', '秦岭冷杉', '二级', 'species', NULL::text[]),
  ('Abies fanjingshanensis', 'abies fanjingshanensis', '梵净山冷杉', '一级', 'species', NULL::text[]),
  ('Abies yuanbaoshanensis', 'abies yuanbaoshanensis', '元宝山冷杉', '一级', 'species', NULL::text[]),
  ('Cathaya argyrophylla', 'cathaya argyrophylla', '银杉', '一级', 'species', NULL::text[]),
  ('Keteleeria spp.', 'keteleeria', '油杉属（所有种，铁坚油杉、云南油杉、油杉除外）', '二级', 'genus', ARRAY['keteleeria davidiana','keteleeria evelyniana','keteleeria fortunei']),
  ('Picea neoveitchii', 'picea neoveitchii', '大果青扦', '二级', 'species', NULL::text[]),
  ('Pinus dabeshanensis', 'pinus dabeshanensis', '大别山五针松', '一级', 'species', NULL::text[]),
  ('Pinus densiflora var. ussuriensis', 'pinus densiflora', '兴凯赤松', '二级', 'species', NULL::text[]),
  ('Pinus koraiensis', 'pinus koraiensis', '红松', '二级', 'species', NULL::text[]),
  ('Pinus kwangtungensis', 'pinus kwangtungensis', '华南五针松', '二级', 'species', NULL::text[]),
  ('Pinus massoniana var. hainanensis', 'pinus massoniana', '雅加松', '二级', 'species', NULL::text[]),
  ('Pinus squamata', 'pinus squamata', '巧家五针松', '一级', 'species', NULL::text[]),
  ('Pinus sylvestris var. sylvestriformis', 'pinus sylvestris', '长白松', '二级', 'species', NULL::text[]),
  ('Pinus wangii', 'pinus wangii', '毛枝五针松', '一级', 'species', NULL::text[]),
  ('Pseudolarix amabilis', 'pseudolarix amabilis', '金钱松', '二级', 'species', NULL::text[]),
  ('Pseudotsuga spp.', 'pseudotsuga', '黄杉属（所有种）', '二级', 'genus', NULL::text[]),
  ('Ephedra rhytidosperma', 'ephedra rhytidosperma', '斑子麻黄', '二级', 'species', NULL::text[]),
  ('Brasenia schreberi', 'brasenia schreberi', '莼菜', '二级', 'species', NULL::text[]),
  ('Nymphaea candida', 'nymphaea candida', '雪白睡莲', '二级', 'species', NULL::text[]),
  ('Illicium difengpi', 'illicium difengpi', '地枫皮', '二级', 'species', NULL::text[]),
  ('Schisandra macrocarpa', 'schisandra macrocarpa', '大果五味子', '二级', 'species', NULL::text[]),
  ('Aristolochia utriformis', 'aristolochia utriformis', '囊花马兜铃', '二级', 'species', NULL::text[]),
  ('Asarum insigne', 'asarum insigne', '金耳环', '二级', 'species', NULL::text[]),
  ('Saruma henryi', 'saruma henryi', '马蹄香', '二级', 'species', NULL::text[]),
  ('Horsfieldia spp.', 'horsfieldia', '风吹楠属（所有种）', '二级', 'genus', NULL::text[]),
  ('Myristica yunnanensis', 'myristica yunnanensis', '云南肉豆蔻', '二级', 'species', NULL::text[]),
  ('Alcimandra cathcartii', 'alcimandra cathcartii', '长蕊木兰', '二级', 'species', NULL::text[]),
  ('Houpoëa officinalis', 'houpoea officinalis', '厚朴', '二级', 'species', NULL::text[]),
  ('Houpoëa rostrata', 'houpoea rostrata', '长喙厚朴', '二级', 'species', NULL::text[]),
  ('Lirianthe henryi', 'lirianthe henryi', '大叶木兰', '二级', 'species', NULL::text[]),
  ('Lirianthe odoratissima', 'lirianthe odoratissima', '馨香玉兰（馨香木兰）', '二级', 'species', NULL::text[]),
  ('Liriodendron chinense', 'liriodendron chinense', '鹅掌楸（马褂木）', '二级', 'species', NULL::text[]),
  ('Manglietia aromatica', 'manglietia aromatica', '香木莲', '二级', 'species', NULL::text[]),
  ('Manglietia dandyi', 'manglietia dandyi', '大叶木莲', '二级', 'species', NULL::text[]),
  ('Manglietia decidua', 'manglietia decidua', '落叶木莲', '二级', 'species', NULL::text[]),
  ('Manglietia grandis', 'manglietia grandis', '大果木莲', '二级', 'species', NULL::text[]),
  ('Manglietia pachyphylla', 'manglietia pachyphylla', '厚叶木莲', '二级', 'species', NULL::text[]),
  ('Manglietia ventii', 'manglietia ventii', '毛果木莲', '二级', 'species', NULL::text[]),
  ('Michelia hypolampra', 'michelia hypolampra', '香子含笑（香籽含笑）', '二级', 'species', NULL::text[]),
  ('Michelia guangdongensis', 'michelia guangdongensis', '广东含笑', '二级', 'species', NULL::text[]),
  ('Michelia shiluensis', 'michelia shiluensis', '石碌含笑', '二级', 'species', NULL::text[]),
  ('Michelia wilsonii', 'michelia wilsonii', '峨眉含笑', '二级', 'species', NULL::text[]),
  ('Oyama sinensis', 'oyama sinensis', '圆叶天女花（圆叶玉兰）', '二级', 'species', NULL::text[]),
  ('Oyama wilsonii', 'oyama wilsonii', '西康天女花（西康玉兰）', '二级', 'species', NULL::text[]),
  ('Pachylarnax sinica', 'pachylarnax sinica', '华盖木', '一级', 'species', NULL::text[]),
  ('Parakmeria omeiensis', 'parakmeria omeiensis', '峨眉拟单性木兰', '一级', 'species', NULL::text[]),
  ('Parakmeria yunnanensis', 'parakmeria yunnanensis', '云南拟单性木兰', '二级', 'species', NULL::text[]),
  ('Paramichelia baillonii', 'paramichelia baillonii', '合果木', '二级', 'species', NULL::text[]),
  ('Woonyoungia septentrionalis', 'woonyoungia septentrionalis', '焕镛木（单性木兰）', '一级', 'species', NULL::text[]),
  ('Yulania zenii', 'yulania zenii', '宝华玉兰', '二级', 'species', NULL::text[]),
  ('Chieniodendron hainanense', 'chieniodendron hainanense', '蕉木', '二级', 'species', NULL::text[]),
  ('Wangia saccopetaloides', 'wangia saccopetaloides', '文采木', '二级', 'species', NULL::text[]),
  ('Calycanthus chinensis', 'calycanthus chinensis', '夏蜡梅', '二级', 'species', NULL::text[]),
  ('Hernandia nymphaeifolia', 'hernandia nymphaeifolia', '莲叶桐', '二级', 'species', NULL::text[]),
  ('Alseodaphne hainanensis', 'alseodaphne hainanensis', '油丹', '二级', 'species', NULL::text[]),
  ('Alseodaphne rugosa', 'alseodaphne rugosa', '皱皮油丹', '二级', 'species', NULL::text[]),
  ('Cinnamomum chago', 'cinnamomum chago', '茶果樟', '二级', 'species', NULL::text[]),
  ('Cinnamomum japonicum', 'cinnamomum japonicum', '天竺桂', '二级', 'species', NULL::text[]),
  ('Cinnamomum longepaniculatum', 'cinnamomum longepaniculatum', '油樟', '二级', 'species', NULL::text[]),
  ('Cinnamomum rigidissimum', 'cinnamomum rigidissimum', '卵叶桂', '二级', 'species', NULL::text[]),
  ('Machilus nanmu', 'machilus nanmu', '润楠', '二级', 'species', NULL::text[]),
  ('Neolitsea sericea', 'neolitsea sericea', '舟山新木姜子', '二级', 'species', NULL::text[]),
  ('Phoebe bournei', 'phoebe bournei', '闽楠', '二级', 'species', NULL::text[]),
  ('Phoebe chekiangensis', 'phoebe chekiangensis', '浙江楠', '二级', 'species', NULL::text[]),
  ('Phoebe hui', 'phoebe hui', '细叶楠', '二级', 'species', NULL::text[]),
  ('Phoebe zhennan', 'phoebe zhennan', '楠木', '二级', 'species', NULL::text[]),
  ('Sinopora hongkongensis', 'sinopora hongkongensis', '孔药楠', '二级', 'species', NULL::text[]),
  ('Butomopsis latifolia', 'butomopsis latifolia', '拟花蔺', '二级', 'species', NULL::text[]),
  ('Ranalisma rostrata', 'ranalisma rostrata', '长喙毛茛泽泻', '二级', 'species', NULL::text[]),
  ('Sagittaria natans', 'sagittaria natans', '浮叶慈菇', '二级', 'species', NULL::text[]),
  ('Najas browniana', 'najas browniana', '高雄茨藻', '二级', 'species', NULL::text[]),
  ('Ottelia spp.', 'ottelia', '海菜花属（所有种）', '二级', 'genus', NULL::text[]),
  ('Scheuchzeria palustris', 'scheuchzeria palustris', '冰沼草', '二级', 'species', NULL::text[]),
  ('Acanthochlamys bracteata', 'acanthochlamys bracteata', '芒苞草', '二级', 'species', NULL::text[]),
  ('Paris spp.', 'paris', '重楼属（所有种，北重楼除外）', '二级', 'genus', ARRAY['paris verticillata']),
  ('Cardiocrinum cathayanum', 'cardiocrinum cathayanum', '荞麦叶大百合', '二级', 'species', NULL::text[]),
  ('Fritillaria spp.', 'fritillaria', '贝母属（所有种）', '二级', 'genus', NULL::text[]),
  ('Lilium amabile', 'lilium amabile', '秀丽百合', '二级', 'species', NULL::text[]),
  ('Lilium fargesii', 'lilium fargesii', '绿花百合', '二级', 'species', NULL::text[]),
  ('Lilium papilliferum', 'lilium papilliferum', '乳头百合', '二级', 'species', NULL::text[]),
  ('Lilium tianschanicum', 'lilium tianschanicum', '天山百合', '二级', 'species', NULL::text[]),
  ('Lilium tsingtauense', 'lilium tsingtauense', '青岛百合', '二级', 'species', NULL::text[]),
  ('Tulipa spp.', 'tulipa', '郁金香属（所有种）', '二级', 'genus', NULL::text[]),
  ('Aerides odorata', 'aerides odorata', '香花指甲兰', '二级', 'species', NULL::text[]),
  ('Anoectochilus spp.', 'anoectochilus', '金线兰属（所有种）', '二级', 'genus', NULL::text[]),
  ('Bletilla striata', 'bletilla striata', '白及', '二级', 'species', NULL::text[]),
  ('Bulbophyllum rothschildianum', 'bulbophyllum rothschildianum', '美花卷瓣兰', '二级', 'species', NULL::text[]),
  ('Calanthe dulongensis', 'calanthe dulongensis', '独龙虾脊兰', '二级', 'species', NULL::text[]),
  ('Calanthe striata var. sieboldii', 'calanthe striata', '大黄花虾脊兰', '一级', 'species', NULL::text[]),
  ('Changnienia amoena', 'changnienia amoena', '独花兰', '二级', 'species', NULL::text[]),
  ('Corybas taliensis', 'corybas taliensis', '大理铠兰', '二级', 'species', NULL::text[]),
  ('Cremastra appendiculata', 'cremastra appendiculata', '杜鹃兰', '二级', 'species', NULL::text[]),
  ('Cymbidium spp.', 'cymbidium', '兰属（所有种，被列入一级保护的美花兰和文山红柱兰除外。兔耳兰未列入名录）', '二级', 'genus', ARRAY['cymbidium insigne','cymbidium wenshanense','cymbidium lancifolium']),
  ('Cymbidium insigne', 'cymbidium insigne', '美花兰', '一级', 'species', NULL::text[]),
  ('Cymbidium wenshanense', 'cymbidium wenshanense', '文山红柱兰', '一级', 'species', NULL::text[]),
  ('Cypripedium spp.', 'cypripedium', '杓兰属（所有种，被列入一级保护的暖地杓兰除外。离萼杓兰未列入名录）', '二级', 'genus', ARRAY['cypripedium subtropicum','cypripedium plectrochilum']),
  ('Cypripedium subtropicum', 'cypripedium subtropicum', '暖地杓兰', '一级', 'species', NULL::text[]),
  ('Danxiaorchis spp.', 'danxiaorchis', '丹霞兰属（所有种）', '二级', 'genus', NULL::text[]),
  ('Dendrobium spp.', 'dendrobium', '石斛属（所有种，被列入一级保护的曲茎石斛和霍山石斛除外）', '二级', 'genus', ARRAY['dendrobium flexicaule','dendrobium huoshanense']),
  ('Dendrobium flexicaule', 'dendrobium flexicaule', '曲茎石斛', '一级', 'species', NULL::text[]),
  ('Dendrobium huoshanense', 'dendrobium huoshanense', '霍山石斛', '一级', 'species', NULL::text[]),
  ('Gastrodia angusta', 'gastrodia angusta', '原天麻', '二级', 'species', NULL::text[]),
  ('Gastrodia elata', 'gastrodia elata', '天麻', '二级', 'species', NULL::text[]),
  ('Gymnadenia conopsea', 'gymnadenia conopsea', '手参', '二级', 'species', NULL::text[]),
  ('Gymnadenia orchidis', 'gymnadenia orchidis', '西南手参', '二级', 'species', NULL::text[]),
  ('Ludisia discolor', 'ludisia discolor', '血叶兰', '二级', 'species', NULL::text[]),
  ('Paphiopedilum spp.', 'paphiopedilum', '兜兰属（所有种，被列入二级保护的带叶兜兰和硬叶兜兰除外）', '一级', 'genus', ARRAY['paphiopedilum hirsutissimum','paphiopedilum micranthum']),
  ('Paphiopedilum hirsutissimum', 'paphiopedilum hirsutissimum', '带叶兜兰', '二级', 'species', NULL::text[]),
  ('Paphiopedilum micranthum', 'paphiopedilum micranthum', '硬叶兜兰', '二级', 'species', NULL::text[]),
  ('Phaius hainanensis', 'phaius hainanensis', '海南鹤顶兰', '二级', 'species', NULL::text[]),
  ('Phaius wenshanensis', 'phaius wenshanensis', '文山鹤顶兰', '二级', 'species', NULL::text[]),
  ('Phalaenopsis lobbii', 'phalaenopsis lobbii', '罗氏蝴蝶兰', '二级', 'species', NULL::text[]),
  ('Phalaenopsis malipoensis', 'phalaenopsis malipoensis', '麻栗坡蝴蝶兰', '二级', 'species', NULL::text[]),
  ('Phalaenopsis wilsonii', 'phalaenopsis wilsonii', '华西蝴蝶兰', '二级', 'species', NULL::text[]),
  ('Phalaenopsis zhejiangensis', 'phalaenopsis zhejiangensis', '象鼻兰', '一级', 'species', NULL::text[]),
  ('Pleione spp.', 'pleione', '独蒜兰属（所有种）', '二级', 'genus', NULL::text[]),
  ('Renanthera spp.', 'renanthera', '火焰兰属（所有种）', '二级', 'genus', NULL::text[]),
  ('Rhynchostylis retusa', 'rhynchostylis retusa', '钻喙兰', '二级', 'species', NULL::text[]),
  ('Vanda coerulea', 'vanda coerulea', '大花万代兰', '二级', 'species', NULL::text[]),
  ('Vanilla shenzhenica', 'vanilla shenzhenica', '深圳香荚兰', '二级', 'species', NULL::text[]),
  ('Iris narcissiflora', 'iris narcissiflora', '水仙花鸢尾', '二级', 'species', NULL::text[]),
  ('Dracaena cambodiana', 'dracaena cambodiana', '海南龙血树', '二级', 'species', NULL::text[]),
  ('Dracaena cochinchinensis', 'dracaena cochinchinensis', '剑叶龙血树', '二级', 'species', NULL::text[]),
  ('Orchidantha insularis', 'orchidantha insularis', '海南兰花蕉', '二级', 'species', NULL::text[]),
  ('Orchidantha yunnanensis', 'orchidantha yunnanensis', '云南兰花蕉', '二级', 'species', NULL::text[]),
  ('Amomum hainanense', 'amomum hainanense', '海南豆蔻', '二级', 'species', NULL::text[]),
  ('Amomum petaloideum', 'amomum petaloideum', '宽丝豆蔻', '二级', 'species', NULL::text[]),
  ('Curcuma exigua', 'curcuma exigua', '细莪术', '二级', 'species', NULL::text[]),
  ('Etlingera yunnanensis', 'etlingera yunnanensis', '茴香砂仁', '二级', 'species', NULL::text[]),
  ('Siliquamomum tonkinense', 'siliquamomum tonkinense', '长果姜', '二级', 'species', NULL::text[]),
  ('Caryota obtusa', 'caryota obtusa', '董棕', '二级', 'species', NULL::text[]),
  ('Chuniophoenix hainanensis', 'chuniophoenix hainanensis', '琼棕', '二级', 'species', NULL::text[]),
  ('Chuniophoenix humilis', 'chuniophoenix humilis', '矮琼棕', '二级', 'species', NULL::text[]),
  ('Nypa fruticans', 'nypa fruticans', '水椰', '二级', 'species', NULL::text[]),
  ('Plectocomia microstachys', 'plectocomia microstachys', '小钩叶藤', '二级', 'species', NULL::text[]),
  ('Trachycarpus nanus', 'trachycarpus nanus', '龙棕', '二级', 'species', NULL::text[]),
  ('Sparganium hyperboreum', 'sparganium hyperboreum', '无柱黑三棱', '二级', 'species', NULL::text[]),
  ('Achnatherum breviaristatum', 'achnatherum breviaristatum', '短芒芨芨草', '二级', 'species', NULL::text[]),
  ('Agropyron mongolicum', 'agropyron mongolicum', '沙芦草', '二级', 'species', NULL::text[]),
  ('Aristida triseta', 'aristida triseta', '三刺草', '二级', 'species', NULL::text[]),
  ('Chikusichloa aquatica', 'chikusichloa aquatica', '山涧草', '二级', 'species', NULL::text[]),
  ('Chimonocalamus fimbriatus', 'chimonocalamus fimbriatus', '流苏香竹', '二级', 'species', NULL::text[]),
  ('Coleanthus subtilis', 'coleanthus subtilis', '莎禾', '二级', 'species', NULL::text[]),
  ('Elymus alashanicus', 'elymus alashanicus', '阿拉善披碱草', '二级', 'species', NULL::text[]),
  ('Elymus atratus', 'elymus atratus', '黑紫披碱草', '二级', 'species', NULL::text[]),
  ('Elymus brevipes', 'elymus brevipes', '短柄披碱草', '二级', 'species', NULL::text[]),
  ('Elymus intramongolicus', 'elymus intramongolicus', '内蒙披碱草', '二级', 'species', NULL::text[]),
  ('Elymus purpuraristatus', 'elymus purpuraristatus', '紫芒披碱草', '二级', 'species', NULL::text[]),
  ('Elymus sinkiangensis', 'elymus sinkiangensis', '新疆披碱草', '二级', 'species', NULL::text[]),
  ('Elymus sinosubmuticus', 'elymus sinosubmuticus', '无芒披碱草', '二级', 'species', NULL::text[]),
  ('Elymus villifer', 'elymus villifer', '毛披碱草', '二级', 'species', NULL::text[]),
  ('Ferrocalamus strictus', 'ferrocalamus strictus', '铁竹', '一级', 'species', NULL::text[]),
  ('Gaoligongshania megalothyrsa', 'gaoligongshania megalothyrsa', '贡山竹', '二级', 'species', NULL::text[]),
  ('Hordeum innermongolicum', 'hordeum innermongolicum', '内蒙古大麦', '二级', 'species', NULL::text[]),
  ('Hsuehochloa calcarea', 'hsuehochloa calcarea', '纪如竹', '二级', 'species', NULL::text[]),
  ('Hygroryza aristata', 'hygroryza aristata', '水禾', '二级', 'species', NULL::text[]),
  ('Kengyilia kokonorica', 'kengyilia kokonorica', '青海以礼草', '二级', 'species', NULL::text[]),
  ('Orinus kokonorica', 'orinus kokonorica', '青海固沙草', '二级', 'species', NULL::text[]),
  ('Oryza spp.', 'oryza', '稻属（所有种）', '二级', 'genus', NULL::text[]),
  ('Psathyrostachys huashanica', 'psathyrostachys huashanica', '华山新麦草', '一级', 'species', NULL::text[]),
  ('Sinochasea trigyna', 'sinochasea trigyna', '三蕊草', '二级', 'species', NULL::text[]),
  ('Sorghum propinquum', 'sorghum propinquum', '拟高梁', '二级', 'species', NULL::text[]),
  ('Spodiopogon sagittifolius', 'spodiopogon sagittifolius', '箭叶大油芒', '二级', 'species', NULL::text[]),
  ('Zoysia sinica', 'zoysia sinica', '中华结缕草', '二级', 'species', NULL::text[]),
  ('Corydalis saxicola', 'corydalis saxicola', '石生黄堇', '二级', 'species', NULL::text[]),
  ('Meconopsis barbiseta', 'meconopsis barbiseta', '久治绿绒蒿', '二级', 'species', NULL::text[]),
  ('Meconopsis punicea', 'meconopsis punicea', '红花绿绒蒿', '二级', 'species', NULL::text[]),
  ('Meconopsis torquata', 'meconopsis torquata', '毛瓣绿绒蒿', '二级', 'species', NULL::text[]),
  ('Arcangelisia gusanlung', 'arcangelisia gusanlung', '古山龙', '二级', 'species', NULL::text[]),
  ('Eleutharrhena macrocarpa', 'eleutharrhena macrocarpa', '藤枣', '二级', 'species', NULL::text[]),
  ('Dysosma spp.', 'dysosma', '八角莲属（所有种）', '二级', 'genus', NULL::text[]),
  ('Mahonia microphylla', 'mahonia microphylla', '小叶十大功劳', '二级', 'species', NULL::text[]),
  ('Mahonia subimbricata', 'mahonia subimbricata', '靖西十大功劳', '二级', 'species', NULL::text[]),
  ('Sinopodophyllum hexandrum', 'sinopodophyllum hexandrum', '桃儿七', '二级', 'species', NULL::text[]),
  ('Kingdonia uniflora', 'kingdonia uniflora', '独叶草', '二级', 'species', NULL::text[]),
  ('Batrachium pekinense', 'batrachium pekinense', '北京水毛茛', '二级', 'species', NULL::text[]),
  ('Clematis acerifolia', 'clematis acerifolia', '槭叶铁线莲', '二级', 'species', NULL::text[]),
  ('Coptis spp.', 'coptis', '黄连属（所有种）', '二级', 'genus', NULL::text[]),
  ('Nelumbo nucifera', 'nelumbo nucifera', '莲', '二级', 'species', NULL::text[]),
  ('Tetracentron sinense', 'tetracentron sinense', '水青树', '二级', 'species', NULL::text[]),
  ('Paeonia sect. Moutan spp.', 'paeonia', '芍药属牡丹组（所有种，被列入一级保护的卵叶牡丹和紫斑牡丹除外，牡丹未列入名录）', '二级', 'section', ARRAY['paeonia qiui','paeonia rockii','paeonia suffruticosa']),
  ('Paeonia qiui', 'paeonia qiui', '卵叶牡丹', '一级', 'species', NULL::text[]),
  ('Paeonia rockii', 'paeonia rockii', '紫斑牡丹', '一级', 'species', NULL::text[]),
  ('Paeonia sterniana', 'paeonia sterniana', '白花芍药', '二级', 'species', NULL::text[]),
  ('Altingia multinervis', 'altingia multinervis', '赤水蕈树', '二级', 'species', NULL::text[]),
  ('Chunia bucklandioides', 'chunia bucklandioides', '山铜材', '二级', 'species', NULL::text[]),
  ('Disanthus cercidifolius subsp. longipes', 'disanthus cercidifolius', '长柄双花木', '二级', 'species', NULL::text[]),
  ('Loropetalum subcordatum', 'loropetalum subcordatum', '四药门花', '二级', 'species', NULL::text[]),
  ('Parrotia subaequalis', 'parrotia subaequalis', '银缕梅', '一级', 'species', NULL::text[]),
  ('Cercidiphyllum japonicum', 'cercidiphyllum japonicum', '连香树', '二级', 'species', NULL::text[]),
  ('Rhodiola angusta', 'rhodiola angusta', '长白红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola crenulata', 'rhodiola crenulata', '大花红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola fastigiata', 'rhodiola fastigiata', '长鞭红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola himalensis', 'rhodiola himalensis', '喜马红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola quadrifida', 'rhodiola quadrifida', '四裂红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola rosea', 'rhodiola rosea', '红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola sachalinensis', 'rhodiola sachalinensis', '库页红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola sacra', 'rhodiola sacra', '圣地红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola tangutica', 'rhodiola tangutica', '唐古红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola wallichiana', 'rhodiola wallichiana', '粗茎红景天', '二级', 'species', NULL::text[]),
  ('Rhodiola yunnanensis', 'rhodiola yunnanensis', '云南红景天', '二级', 'species', NULL::text[]),
  ('Myriophyllum ussuriense', 'myriophyllum ussuriense', '乌苏里狐尾藻', '二级', 'species', NULL::text[]),
  ('Cynomorium songaricum', 'cynomorium songaricum', '锁阳', '二级', 'species', NULL::text[]),
  ('Vitis baihuashanensis', 'vitis baihuashanensis', '百花山葡萄', '一级', 'species', NULL::text[]),
  ('Vitis zhejiang-adstricta', 'vitis zhejiang-adstricta', '浙江蘡薁', '二级', 'species', NULL::text[]),
  ('Tetraena mongolica', 'tetraena mongolica', '四合木', '二级', 'species', NULL::text[]),
  ('Ammopiptanthus mongolicus', 'ammopiptanthus mongolicus', '沙冬青', '二级', 'species', NULL::text[]),
  ('Archidendron robinsonii', 'archidendron robinsonii', '棋子豆', '二级', 'species', NULL::text[]),
  ('Bauhinia cercidifolia', 'bauhinia cercidifolia', '紫荆叶羊蹄甲', '二级', 'species', NULL::text[]),
  ('Calophaca sinica', 'calophaca sinica', '丽豆', '二级', 'species', NULL::text[]),
  ('Dalbergia cultrata', 'dalbergia cultrata', '黑黄檀', '二级', 'species', NULL::text[]),
  ('Dalbergia hainanensis', 'dalbergia hainanensis', '海南黄檀', '二级', 'species', NULL::text[]),
  ('Dalbergia odorifera', 'dalbergia odorifera', '降香', '二级', 'species', NULL::text[]),
  ('Dalbergia ovata', 'dalbergia ovata', '卵叶黄檀', '二级', 'species', NULL::text[]),
  ('Erythrophleum fordii', 'erythrophleum fordii', '格木', '二级', 'species', NULL::text[]),
  ('Euchresta japonica', 'euchresta japonica', '山豆根', '二级', 'species', NULL::text[]),
  ('Gleditsia japonica var. velutina', 'gleditsia japonica', '绒毛皂荚', '一级', 'species', NULL::text[]),
  ('Glycine soja', 'glycine soja', '野大豆', '二级', 'species', NULL::text[]),
  ('Glycine tabacina', 'glycine tabacina', '烟豆', '二级', 'species', NULL::text[]),
  ('Glycine tomentella', 'glycine tomentella', '短绒野大豆', '二级', 'species', NULL::text[]),
  ('Glycyrrhiza inflata', 'glycyrrhiza inflata', '胀果甘草', '二级', 'species', NULL::text[]),
  ('Glycyrrhiza uralensis', 'glycyrrhiza uralensis', '甘草', '二级', 'species', NULL::text[]),
  ('Maackia chekiangensis', 'maackia chekiangensis', '浙江马鞍树', '二级', 'species', NULL::text[]),
  ('Ormosia spp.', 'ormosia', '红豆属(所有种，被列入一级保护的小叶红豆除外。)', '二级', 'genus', ARRAY['ormosia microphylla']),
  ('Ormosia microphylla', 'ormosia microphylla', '小叶红豆', '一级', 'species', NULL::text[]),
  ('Salweenia spp.', 'salweenia', '冬麻豆属(所有种)', '二级', 'genus', NULL::text[]),
  ('Sindora glabra', 'sindora glabra', '油楠', '二级', 'species', NULL::text[]),
  ('Sophora tonkinensis', 'sophora tonkinensis', '越南槐', '二级', 'species', NULL::text[]),
  ('Suriana maritima', 'suriana maritima', '海人树', '二级', 'species', NULL::text[]),
  ('Geum rupestre', 'geum rupestre', '太行花', '二级', 'species', NULL::text[]),
  ('Malus komarovii', 'malus komarovii', '山楂海棠', '二级', 'species', NULL::text[]),
  ('Malus rockii', 'malus rockii', '丽江山荆子', '二级', 'species', NULL::text[]),
  ('Malus sieversii', 'malus sieversii', '新疆野苹果', '二级', 'species', NULL::text[]),
  ('Malus sikkimensis', 'malus sikkimensis', '锡金海棠', '二级', 'species', NULL::text[]),
  ('Potaninia mongolica', 'potaninia mongolica', '绵刺', '二级', 'species', NULL::text[]),
  ('Prunus armeniaca', 'prunus armeniaca', '新疆野杏', '二级', 'species', NULL::text[]),
  ('Prunus cerasifera', 'prunus cerasifera', '新疆樱桃李', '二级', 'species', NULL::text[]),
  ('Prunus kansuensis', 'prunus kansuensis', '甘肃桃', '二级', 'species', NULL::text[]),
  ('Prunus mongolica', 'prunus mongolica', '蒙古扁桃', '二级', 'species', NULL::text[]),
  ('Prunus mira', 'prunus mira', '光核桃', '二级', 'species', NULL::text[]),
  ('Prunus nana', 'prunus nana', '矮扁桃（野巴旦，野扁桃）', '二级', 'species', NULL::text[]),
  ('Prunus zhengheensis', 'prunus zhengheensis', '政和杏', '二级', 'species', NULL::text[]),
  ('Rosa anemoniflora', 'rosa anemoniflora', '银粉蔷薇', '二级', 'species', NULL::text[]),
  ('Rosa berberifolia', 'rosa berberifolia', '小檗叶蔷薇', '二级', 'species', NULL::text[]),
  ('Rosa chinensis var. spontanea', 'rosa chinensis', '单瓣月季花', '二级', 'species', NULL::text[]),
  ('Rosa kwangtungensis', 'rosa kwangtungensis', '广东蔷薇', '二级', 'species', NULL::text[]),
  ('Rosa lucidissima', 'rosa lucidissima', '亮叶月季', '二级', 'species', NULL::text[]),
  ('Rosa odorata var. gigantea', 'rosa odorata', '大花香水月季', '二级', 'species', NULL::text[]),
  ('Rosa praelucens', 'rosa praelucens', '中甸刺玫', '二级', 'species', NULL::text[]),
  ('Rosa rugosa', 'rosa rugosa', '玫瑰', '二级', 'species', NULL::text[]),
  ('Elaeagnus mollis', 'elaeagnus mollis', '翅果油树', '二级', 'species', NULL::text[]),
  ('Berchemiella wilsonii', 'berchemiella wilsonii', '小勾儿茶', '二级', 'species', NULL::text[]),
  ('Ulmus elongata', 'ulmus elongata', '长序榆', '二级', 'species', NULL::text[]),
  ('Zelkova schneideriana', 'zelkova schneideriana', '大叶榉树', '二级', 'species', NULL::text[]),
  ('Artocarpus nanchuanensis', 'artocarpus nanchuanensis', '南川木波罗', '二级', 'species', NULL::text[]),
  ('Morus macroura', 'morus macroura', '奶桑', '二级', 'species', NULL::text[]),
  ('Morus notabilis', 'morus notabilis', '川桑', '二级', 'species', NULL::text[]),
  ('Morus wittiorum', 'morus wittiorum', '长穗桑', '二级', 'species', NULL::text[]),
  ('Boehmeria leiophylla', 'boehmeria leiophylla', '光叶苎麻', '二级', 'species', NULL::text[]),
  ('Boehmeria oblongifolia', 'boehmeria oblongifolia', '长圆苎麻', '二级', 'species', NULL::text[]),
  ('Castanopsis concinna', 'castanopsis concinna', '华南锥', '二级', 'species', NULL::text[]),
  ('Cyclobalanopsis sichourensis', 'cyclobalanopsis sichourensis', '西畴青冈', '二级', 'species', NULL::text[]),
  ('Fagus hayatae', 'fagus hayatae', '台湾水青冈', '二级', 'species', NULL::text[]),
  ('Formanodendron doichangensis', 'formanodendron doichangensis', '三棱栎', '二级', 'species', NULL::text[]),
  ('Quercus bawanglingensis', 'quercus bawanglingensis', '霸王栎', '二级', 'species', NULL::text[]),
  ('Quercus oxyphylla', 'quercus oxyphylla', '尖叶栎', '二级', 'species', NULL::text[]),
  ('Annamocarya sinensis', 'annamocarya sinensis', '喙核桃', '二级', 'species', NULL::text[]),
  ('Carya kweichowensis', 'carya kweichowensis', '贵州山核桃', '二级', 'species', NULL::text[]),
  ('Carpinus putoensis', 'carpinus putoensis', '普陀鹅耳枥', '一级', 'species', NULL::text[]),
  ('Carpinus tientaiensis', 'carpinus tientaiensis', '天台鹅耳枥', '二级', 'species', NULL::text[]),
  ('Ostrya rehderiana', 'ostrya rehderiana', '天目铁木', '一级', 'species', NULL::text[]),
  ('Cucumis sativus var. xishuangbannanensis', 'cucumis sativus', '野黄瓜', '二级', 'species', NULL::text[]),
  ('Tetrameles nudiflora', 'tetrameles nudiflora', '四数木', '二级', 'species', NULL::text[]),
  ('Begonia arachnoidea', 'begonia arachnoidea', '蛛网脉秋海棠', '二级', 'species', NULL::text[]),
  ('Begonia coptidifolia', 'begonia coptidifolia', '阳春秋海棠', '二级', 'species', NULL::text[]),
  ('Begonia ferox', 'begonia ferox', '黑峰秋海棠', '二级', 'species', NULL::text[]),
  ('Begonia gulinqingensis', 'begonia gulinqingensis', '古林箐秋海棠', '二级', 'species', NULL::text[]),
  ('Begonia gulongshanensis', 'begonia gulongshanensis', '古龙山秋海棠', '二级', 'species', NULL::text[]),
  ('Begonia hainanensis', 'begonia hainanensis', '海南秋海棠', '二级', 'species', NULL::text[]),
  ('Begonia hongkongensis', 'begonia hongkongensis', '香港秋海棠', '二级', 'species', NULL::text[]),
  ('Monimopetalum chinense', 'monimopetalum chinense', '永瓣藤', '二级', 'species', NULL::text[]),
  ('Plagiopteron suaveolens', 'plagiopteron suaveolens', '斜翼', '二级', 'species', NULL::text[]),
  ('Bhesa robusta', 'bhesa robusta', '膝柄木', '一级', 'species', NULL::text[]),
  ('Sauvagesia rhodoleuca', 'sauvagesia rhodoleuca', '合柱金莲木', '二级', 'species', NULL::text[]),
  ('Cladopus spp.', 'cladopus', '川苔草属（所有种）', '二级', 'genus', NULL::text[]),
  ('Dalzellia spp.', 'dalzellia', '川藻属（所有种）', '二级', 'genus', NULL::text[]),
  ('Hydrobryum griffithii', 'hydrobryum griffithii', '水石衣', '二级', 'species', NULL::text[]),
  ('Garcinia paucinervis', 'garcinia paucinervis', '金丝李', '二级', 'species', NULL::text[]),
  ('Garcinia tetralata', 'garcinia tetralata', '双籽藤黄', '二级', 'species', NULL::text[]),
  ('Hydnocarpus hainanensis', 'hydnocarpus hainanensis', '海南大风子', '二级', 'species', NULL::text[]),
  ('Populus × irtyschensis', 'populus x', '额河杨', '二级', 'species', NULL::text[]),
  ('Sapria himalayana', 'sapria himalayana', '寄生花', '二级', 'species', NULL::text[]),
  ('Deutzianthus tonkinensis', 'deutzianthus tonkinensis', '东京桐', '二级', 'species', NULL::text[]),
  ('Getonia floribunda', 'getonia floribunda', '萼翅藤', '一级', 'species', NULL::text[]),
  ('Lumnitzera littorea', 'lumnitzera littorea', '红榄李', '一级', 'species', NULL::text[]),
  ('Terminalia myriocarpa', 'terminalia myriocarpa', '千果榄仁', '二级', 'species', NULL::text[]),
  ('Lagerstroemia minuticarpa', 'lagerstroemia minuticarpa', '小果紫薇', '二级', 'species', NULL::text[]),
  ('Lagerstroemia villosa', 'lagerstroemia villosa', '毛紫薇', '二级', 'species', NULL::text[]),
  ('Pemphis acidula', 'pemphis acidula', '水芫花', '二级', 'species', NULL::text[]),
  ('Trapa incisa', 'trapa incisa', '细果野菱（野菱）', '二级', 'species', NULL::text[]),
  ('Tigridiopalma magnifica', 'tigridiopalma magnifica', '虎颜花', '二级', 'species', NULL::text[]),
  ('Mangifera sylvatica', 'mangifera sylvatica', '林生杧果', '二级', 'species', NULL::text[]),
  ('Acer amplum subsp. catalpifolium', 'acer amplum', '梓叶槭', '二级', 'species', NULL::text[]),
  ('Acer miaotaiense', 'acer miaotaiense', '庙台槭', '二级', 'species', NULL::text[]),
  ('Acer pentaphyllum', 'acer pentaphyllum', '五小叶槭', '二级', 'species', NULL::text[]),
  ('Acer yangbiense', 'acer yangbiense', '漾濞槭', '二级', 'species', NULL::text[]),
  ('Dimocarpus longan', 'dimocarpus longan', '龙眼', '二级', 'species', NULL::text[]),
  ('Dipteronia dyeriana', 'dipteronia dyeriana', '云南金钱槭', '二级', 'species', NULL::text[]),
  ('Eurycorymbus cavaleriei', 'eurycorymbus cavaleriei', '伞花木', '二级', 'species', NULL::text[]),
  ('Handeliodendron bodinieri', 'handeliodendron bodinieri', '掌叶木', '二级', 'species', NULL::text[]),
  ('Lepisanthes unilocularis', 'lepisanthes unilocularis', '爪耳木', '二级', 'species', NULL::text[]),
  ('Litchi chinensis var. euspontanea', 'litchi chinensis', '野生荔枝', '二级', 'species', NULL::text[]),
  ('Nephelium chryseum', 'nephelium chryseum', '韶子', '二级', 'species', NULL::text[]),
  ('Paranephelium hainanense', 'paranephelium hainanense', '海南假韶子', '二级', 'species', NULL::text[]),
  ('Citrus cavaleriei', 'citrus cavaleriei', '宜昌橙', '二级', 'species', NULL::text[]),
  ('Citrus daoxianensis', 'citrus daoxianensis', '道县野桔', '二级', 'species', NULL::text[]),
  ('Citrus hongheensis', 'citrus hongheensis', '红河橙', '二级', 'species', NULL::text[]),
  ('Citrus mangshanensis', 'citrus mangshanensis', '莽山野桔', '二级', 'species', NULL::text[]),
  ('Fortunella hindsii', 'fortunella hindsii', '山橘', '二级', 'species', NULL::text[]),
  ('Fortunella venosa', 'fortunella venosa', '金豆', '二级', 'species', NULL::text[]),
  ('Phellodendron amurense', 'phellodendron amurense', '黄檗', '二级', 'species', NULL::text[]),
  ('Phellodendron chinense', 'phellodendron chinense', '川黄檗', '二级', 'species', NULL::text[]),
  ('Poncirus × polyandra', 'poncirus x', '富民枳', '二级', 'species', NULL::text[]),
  ('Aglaia lawii', 'aglaia lawii', '望谟崖摩', '二级', 'species', NULL::text[]),
  ('Toona ciliata', 'toona ciliata', '红椿', '二级', 'species', NULL::text[]),
  ('Xylocarpus granatum', 'xylocarpus granatum', '木果楝', '二级', 'species', NULL::text[]),
  ('Burretiodendron esquirolii', 'burretiodendron esquirolii', '柄翅果', '二级', 'species', NULL::text[]),
  ('Craigia yunnanensis', 'craigia yunnanensis', '滇桐', '二级', 'species', NULL::text[]),
  ('Diplodiscus trichospermus', 'diplodiscus trichospermus', '海南椴', '二级', 'species', NULL::text[]),
  ('Excentrodendron tonkinense', 'excentrodendron tonkinense', '蚬木', '二级', 'species', NULL::text[]),
  ('Erythropsis kwangsiensis', 'erythropsis kwangsiensis', '广西火桐', '一级', 'species', NULL::text[]),
  ('Firmiana spp.', 'firmiana', '梧桐属（所有种，梧桐除外）', '二级', 'genus', ARRAY['firmiana simplex']),
  ('Heritiera parvifolia', 'heritiera parvifolia', '蝴蝶树', '二级', 'species', NULL::text[]),
  ('Paradombeya sinensis', 'paradombeya sinensis', '平当树', '二级', 'species', NULL::text[]),
  ('Pterospermum kingtungense', 'pterospermum kingtungense', '景东翅子树', '二级', 'species', NULL::text[]),
  ('Pterospermum menglunense', 'pterospermum menglunense', '勐仑翅子树', '二级', 'species', NULL::text[]),
  ('Reevesia rotundifolia', 'reevesia rotundifolia', '粗齿梭罗', '二级', 'species', NULL::text[]),
  ('Tilia amurensis', 'tilia amurensis', '紫椴', '二级', 'species', NULL::text[]),
  ('Aquilaria sinensis', 'aquilaria sinensis', '土沉香', '二级', 'species', NULL::text[]),
  ('Aquilaria yunnanensis', 'aquilaria yunnanensis', '云南沉香', '二级', 'species', NULL::text[]),
  ('Helianthemum songaricum', 'helianthemum songaricum', '半日花', '二级', 'species', NULL::text[]),
  ('Dipterocarpus retusus', 'dipterocarpus retusus', '东京龙脑香', '一级', 'species', NULL::text[]),
  ('Hopea chinensis', 'hopea chinensis', '狭叶坡垒', '二级', 'species', NULL::text[]),
  ('Hopea hainanensis', 'hopea hainanensis', '坡垒', '一级', 'species', NULL::text[]),
  ('Hopea reticulata', 'hopea reticulata', '翼坡垒(铁凌)', '二级', 'species', NULL::text[]),
  ('Hopea shingkeng', 'hopea shingkeng', '西藏坡垒', '二级', 'species', NULL::text[]),
  ('Parashorea chinensis', 'parashorea chinensis', '望天树', '一级', 'species', NULL::text[]),
  ('Shorea assamica', 'shorea assamica', '云南娑罗双', '一级', 'species', NULL::text[]),
  ('Vatica guangxiensis', 'vatica guangxiensis', '广西青梅', '一级', 'species', NULL::text[]),
  ('Vatica mangachapoi', 'vatica mangachapoi', '青梅', '二级', 'species', NULL::text[]),
  ('Bretschneidera sinensis', 'bretschneidera sinensis', '伯乐树（钟萼木）', '二级', 'species', NULL::text[]),
  ('Malania oleifera', 'malania oleifera', '蒜头果', '二级', 'species', NULL::text[]),
  ('Frankenia pulverulenta', 'frankenia pulverulenta', '瓣鳞花', '二级', 'species', NULL::text[]),
  ('Myricaria laxiflora', 'myricaria laxiflora', '疏花水柏枝', '二级', 'species', NULL::text[]),
  ('Fagopyrum dibotrys', 'fagopyrum dibotrys', '金荞麦', '二级', 'species', NULL::text[]),
  ('Aldrovanda vesiculosa', 'aldrovanda vesiculosa', '貉藻', '一级', 'species', NULL::text[]),
  ('Psammosilene tunicoides', 'psammosilene tunicoides', '金铁锁', '二级', 'species', NULL::text[]),
  ('Baolia bracteata', 'baolia bracteata', '苞藜', '二级', 'species', NULL::text[]),
  ('Cornulaca alaschanica', 'cornulaca alaschanica', '阿拉善单刺蓬', '二级', 'species', NULL::text[]),
  ('Davidia involucrata', 'davidia involucrata', '珙桐', '一级', 'species', NULL::text[]),
  ('Nyssa yunnanensis', 'nyssa yunnanensis', '云南蓝果树', '一级', 'species', NULL::text[]),
  ('Kirengeshoma palmata', 'kirengeshoma palmata', '黄山梅', '二级', 'species', NULL::text[]),
  ('Platycrater arguta', 'platycrater arguta', '蛛网萼', '二级', 'species', NULL::text[]),
  ('Euryodendron excelsum', 'euryodendron excelsum', '猪血木', '一级', 'species', NULL::text[]),
  ('Diploknema yunnanensis', 'diploknema yunnanensis', '滇藏榄', '一级', 'species', NULL::text[]),
  ('Madhuca hainanensis', 'madhuca hainanensis', '海南紫荆木', '二级', 'species', NULL::text[]),
  ('Madhuca pasquieri', 'madhuca pasquieri', '紫荆木', '二级', 'species', NULL::text[]),
  ('Diospyros minutisepala', 'diospyros minutisepala', '小萼柿', '二级', 'species', NULL::text[]),
  ('Diospyros sutchuensis', 'diospyros sutchuensis', '川柿', '二级', 'species', NULL::text[]),
  ('Pomatosace filicula', 'pomatosace filicula', '羽叶点地梅', '二级', 'species', NULL::text[]),
  ('Apterosperma oblata', 'apterosperma oblata', '圆籽荷', '二级', 'species', NULL::text[]),
  ('Camellia azalea', 'camellia azalea', '杜鹃红山茶', '一级', 'species', NULL::text[]),
  ('Camellia sect. Chrysantha spp.', 'camellia', '山茶属金花茶组（所有种）', '二级', 'section', NULL::text[]),
  ('Camellia sect. Thea spp.', 'camellia', '山茶属茶组（所有种, 大叶茶、大理茶除外）', '二级', 'section', ARRAY['camellia sinensis','camellia taliensis']),
  ('Camellia sinensis var. assamica', 'camellia sinensis', '大叶茶', '二级', 'species', NULL::text[]),
  ('Camellia taliensis', 'camellia taliensis', '大理茶', '二级', 'species', NULL::text[]),
  ('Sinojackia spp.', 'sinojackia', '秤锤树属（所有种）', '二级', 'genus', NULL::text[]),
  ('Actinidia arguta', 'actinidia arguta', '软枣猕猴桃', '二级', 'species', NULL::text[]),
  ('Actinidia chinensis', 'actinidia chinensis', '中华猕猴桃', '二级', 'species', NULL::text[]),
  ('Actinidia chrysantha', 'actinidia chrysantha', '金花猕猴桃', '二级', 'species', NULL::text[]),
  ('Actinidia fortunatii', 'actinidia fortunatii', '条叶猕猴桃', '二级', 'species', NULL::text[]),
  ('Actinidia macrosperma', 'actinidia macrosperma', '大籽猕猴桃', '二级', 'species', NULL::text[]),
  ('Rhododendron dauricum', 'rhododendron dauricum', '兴安杜鹃', '二级', 'species', NULL::text[]),
  ('Rhododendron griersonianum', 'rhododendron griersonianum', '朱红大杜鹃', '二级', 'species', NULL::text[]),
  ('Rhododendron huadingense', 'rhododendron huadingense', '华顶杜鹃', '二级', 'species', NULL::text[]),
  ('Rhododendron jingangshanicum', 'rhododendron jingangshanicum', '井冈山杜鹃', '二级', 'species', NULL::text[]),
  ('Rhododendron kiangsiense', 'rhododendron kiangsiense', '江西杜鹃', '二级', 'species', NULL::text[]),
  ('Rhododendron urophyllum', 'rhododendron urophyllum', '尾叶杜鹃', '二级', 'species', NULL::text[]),
  ('Rhododendron williamsianum', 'rhododendron williamsianum', '圆叶杜鹃', '二级', 'species', NULL::text[]),
  ('Dunnia sinensis', 'dunnia sinensis', '绣球茜', '二级', 'species', NULL::text[]),
  ('Emmenopterys henryi', 'emmenopterys henryi', '香果树', '二级', 'species', NULL::text[]),
  ('Morinda officinalis', 'morinda officinalis', '巴戟天', '二级', 'species', NULL::text[]),
  ('Neonauclea tsaiana', 'neonauclea tsaiana', '滇南新乌檀', '二级', 'species', NULL::text[]),
  ('Lomatogoniopsis alpina', 'lomatogoniopsis alpina', '辐花', '二级', 'species', NULL::text[]),
  ('Merrillanthus hainanensis', 'merrillanthus hainanensis', '驼峰藤', '二级', 'species', NULL::text[]),
  ('Parepigynum funingense', 'parepigynum funingense', '富宁藤', '二级', 'species', NULL::text[]),
  ('Arnebia euchroma', 'arnebia euchroma', '新疆紫草', '二级', 'species', NULL::text[]),
  ('Cordia subcordata', 'cordia subcordata', '橙花破布木', '二级', 'species', NULL::text[]),
  ('Lycium ruthenicum', 'lycium ruthenicum', '黑果枸杞', '二级', 'species', NULL::text[]),
  ('Lycium yunnanense', 'lycium yunnanense', '云南枸杞', '二级', 'species', NULL::text[]),
  ('Fraxinus mandschurica', 'fraxinus mandschurica', '水曲柳', '二级', 'species', NULL::text[]),
  ('Fraxinus sogdiana', 'fraxinus sogdiana', '天山梣', '二级', 'species', NULL::text[]),
  ('Osmanthus pubipedicellatus', 'osmanthus pubipedicellatus', '毛柄木犀', '二级', 'species', NULL::text[]),
  ('Osmanthus venosus', 'osmanthus venosus', '毛木犀', '二级', 'species', NULL::text[]),
  ('Dayaoshania cotinifolia', 'dayaoshania cotinifolia', '瑶山苣苔', '二级', 'species', NULL::text[]),
  ('Petrocosmea qinlingensis', 'petrocosmea qinlingensis', '秦岭石蝴蝶', '二级', 'species', NULL::text[]),
  ('Primulina tabacum', 'primulina tabacum', '报春苣苔', '二级', 'species', NULL::text[]),
  ('Thamnocharis esquirolii', 'thamnocharis esquirolii', '辐花苣苔', '一级', 'species', NULL::text[]),
  ('Neopicrorhiza scrophulariiflora', 'neopicrorhiza scrophulariiflora', '胡黄连', '二级', 'species', NULL::text[]),
  ('Plantago fengdouensis', 'plantago fengdouensis', '丰都车前', '二级', 'species', NULL::text[]),
  ('Scrophularia stylosa', 'scrophularia stylosa', '长柱玄参', '二级', 'species', NULL::text[]),
  ('Utricularia punctata', 'utricularia punctata', '盾鳞狸藻', '二级', 'species', NULL::text[]),
  ('Gmelina hainanensis', 'gmelina hainanensis', '苦梓', '二级', 'species', NULL::text[]),
  ('Wenchengia alternifolia', 'wenchengia alternifolia', '保亭花', '二级', 'species', NULL::text[]),
  ('Boschniakia rossica', 'boschniakia rossica', '草苁蓉', '二级', 'species', NULL::text[]),
  ('Cistanche deserticola', 'cistanche deserticola', '肉苁蓉', '二级', 'species', NULL::text[]),
  ('Cistanche mongolica', 'cistanche mongolica', '管花肉苁蓉', '二级', 'species', NULL::text[]),
  ('Triaenophora rupestris', 'triaenophora rupestris', '崖白菜', '二级', 'species', NULL::text[]),
  ('Ilex kaushue', 'ilex kaushue', '扣树', '二级', 'species', NULL::text[]),
  ('Echinocodon draco', 'echinocodon draco', '刺萼参', '二级', 'species', NULL::text[]),
  ('Leucomeris decora', 'leucomeris decora', '白菊木', '二级', 'species', NULL::text[]),
  ('Saussurea balangshanensis', 'saussurea balangshanensis', '巴朗山雪莲', '二级', 'species', NULL::text[]),
  ('Saussurea gossipiphora', 'saussurea gossipiphora', '雪兔子', '二级', 'species', NULL::text[]),
  ('Saussurea involucrata', 'saussurea involucrata', '雪莲', '二级', 'species', NULL::text[]),
  ('Saussurea laniceps', 'saussurea laniceps', '绵头雪兔子', '二级', 'species', NULL::text[]),
  ('Saussurea medusa', 'saussurea medusa', '水母雪兔子', '二级', 'species', NULL::text[]),
  ('Saussurea orgaadayi', 'saussurea orgaadayi', '阿尔泰雪莲', '二级', 'species', NULL::text[]),
  ('Tugarinovia mongolica', 'tugarinovia mongolica', '革苞菊', '二级', 'species', NULL::text[]),
  ('Heptacodium miconioides', 'heptacodium miconioides', '七子花', '二级', 'species', NULL::text[]),
  ('Lonicera oblata', 'lonicera oblata', '丁香叶忍冬', '二级', 'species', NULL::text[]),
  ('Nardostachys jatamansi', 'nardostachys jatamansi', '匙叶甘松', '二级', 'species', NULL::text[]),
  ('Panax spp.', 'panax', '人参属（所有种）', '二级', 'genus', NULL::text[]),
  ('Sinopanax formosanus', 'sinopanax formosanus', '华参', '二级', 'species', NULL::text[]),
  ('Carlesia sinensis', 'carlesia sinensis', '山茴香', '二级', 'species', NULL::text[]),
  ('Changium smyrnioides', 'changium smyrnioides', '明党参', '二级', 'species', NULL::text[]),
  ('Chuanminshen violaceum', 'chuanminshen violaceum', '川明参', '二级', 'species', NULL::text[]),
  ('Ferula fukanensis', 'ferula fukanensis', '阜康阿魏', '二级', 'species', NULL::text[]),
  ('Ferula moschata', 'ferula moschata', '麝香阿魏', '二级', 'species', NULL::text[]),
  ('Ferula sinkiangensis', 'ferula sinkiangensis', '新疆阿魏', '二级', 'species', NULL::text[]),
  ('Glehnia littoralis', 'glehnia littoralis', '珊瑚菜（北沙参）', '二级', 'species', NULL::text[]),
  ('Sargassum naozhouense', 'sargassum naozhouense', '硇洲马尾藻', '二级', 'species', NULL::text[]),
  ('Sargassum nigrifolioides', 'sargassum nigrifolioides', '黑叶马尾藻', '二级', 'species', NULL::text[]),
  ('Silvetia siliquosa', 'silvetia siliquosa', '鹿角菜', '二级', 'species', NULL::text[]),
  ('Eucheuma okamurai', 'eucheuma okamurai', '珍珠麒麟菜', '一级', 'species', NULL::text[]),
  ('Kappaphycus cottonii', 'kappaphycus cottonii', '耳突卡帕藻', '二级', 'species', NULL::text[]),
  ('Nostoc flagelliforme', 'nostoc flagelliforme', '发菜', '一级', 'species', NULL::text[]),
  ('Ophiocordyceps sinensis', 'ophiocordyceps sinensis', '虫草（冬虫夏草）', '二级', 'species', NULL::text[]),
  ('Leucocalocybe mongolica', 'leucocalocybe mongolica', '蒙古口蘑', '二级', 'species', NULL::text[]),
  ('Tricholoma matsutake', 'tricholoma matsutake', '松口蘑（松茸）', '二级', 'species', NULL::text[]),
  ('Tuber sinoaestivum', 'tuber sinoaestivum', '中华夏块菌', '二级', 'species', NULL::text[])
) AS v(sci, norm, zh, status, rank, excl);
